{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":25272071,"authorName":"Sean Timm","from":"Sean Timm &lt;timmsc@...&gt;","profile":"timmscgroups","replyTo":"LIST","senderId":"YnrJz2KYCjJtErW_lKA0SkzpRnoYD2Rf9VE0kLm_CLNVtlsC1J0bgQRgkcPVa11P5JqF9tKDrAgAFA9QkHngeD0","spamInfo":{"isSpam":false,"reason":"12"},"subject":"Re: [archive-crawler] Change request for Heritrix 2.0","postDate":"1204227049","msgId":5017,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PDQ3QzcwQkU5LjQwMDAzMDhAYW9sLmNvbT4=","inReplyToHeader":"PDQ3QzcwQjVELjcwMjAxMDJAYXJjaGl2ZS5vcmc+","referencesHeader":"PGZxNzFoZisxMHFjNUBlR3JvdXBzLmNvbT4gPDQ3QzcwQjVELjcwMjAxMDJAYXJjaGl2ZS5vcmc+"},"prevInTopic":5016,"nextInTopic":5018,"prevInTime":5016,"nextInTime":5018,"topicId":5015,"numMessagesInTopic":9,"msgSnippet":"I agree the throw new RuntimeException( e ); is better than just wrapping the message.  You don t want to lose the original stack. -Sean","rawEmail":"Return-Path: &lt;Timmsc@...&gt;\r\nX-Sender: Timmsc@...\r\nX-Apparently-To: archive-crawler@yahoogroups.com\r\nX-Received: (qmail 39483 invoked from network); 28 Feb 2008 19:31:30 -0000\r\nX-Received: from unknown (66.218.67.96)\n  by m54.grp.scd.yahoo.com with QMQP; 28 Feb 2008 19:31:30 -0000\r\nX-Received: from unknown (HELO imo-m28.mx.aol.com) (64.12.137.9)\n  by mta17.grp.scd.yahoo.com with SMTP; 28 Feb 2008 19:31:30 -0000\r\nX-Received: from Timmsc@...\n\tby imo-m28.mx.aol.com (mail_out_v38_r9.3.) id r.c55.29a5b006 (37108)\n\t for &lt;archive-crawler@yahoogroups.com&gt;; Thu, 28 Feb 2008 14:30:51 -0500 (EST)\r\nX-Received: from [10.181.176.98] ([10.181.176.98]) by cia-db08.mx.aol.com (v121.4) with ESMTP id MAILCIADB086-90f447c70beafa; Thu, 28 Feb 2008 14:30:50 -0500\r\nMessage-ID: &lt;47C70BE9.4000308@...&gt;\r\nDate: Thu, 28 Feb 2008 14:30:49 -0500\r\nUser-Agent: Thunderbird 2.0.0.12 (Windows/20080213)\r\nMIME-Version: 1.0\r\nTo: archive-crawler@yahoogroups.com\r\nReferences: &lt;fq71hf+10qc5@...&gt; &lt;47C70B5D.7020102@...&gt;\r\nIn-Reply-To: &lt;47C70B5D.7020102@...&gt;\r\nContent-Type: text/plain; charset=ISO-8859-1; format=flowed\r\nContent-Transfer-Encoding: 7bit\r\nX-AOL-IP: 10.181.176.98\r\nX-Mailer: Unknown (No Version)\r\nX-Spam-Flag: NO\r\nX-eGroups-Msg-Info: 1:12:0:0:0\r\nFrom: Sean Timm &lt;timmsc@...&gt;\r\nSubject: Re: [archive-crawler] Change request for Heritrix 2.0\r\nX-Yahoo-Group-Post: member; u=25272071; y=EMv6mDZbWW_jxjxwIlBSm2he5Wyp1nHMfAUdajS0aE4s-ZbWbJe_\r\nX-Yahoo-Profile: timmscgroups\r\n\r\nI agree the throw new RuntimeException( e ); is better than just \nwrapping the message.  You don&#39;t want to lose the original stack.\n\n-Sean\n\nGordon Mohr wrote:\n&gt; Good idea!\n&gt;\n&gt; To contribute patches, opening a JIRA issue is the best first step: \n&gt; describe the need, attach the patch, and assign the issue a high \n&gt; priority to help it be noticed in our reviews of open issues. Mentioning \n&gt; the matter here is also welcome.\n&gt;\n&gt; Regarding the proposed change:\n&gt;\n&gt; Might using the RuntimeException constructor that wraps another \n&gt; exception (the &#39;cause&#39;), effectively retain the original message and stack?\n&gt;\n&gt; For example:\n&gt;\n&gt;    catch( NullPointerException e ) {\n&gt;       // do some stuff\n&gt;       throw new RuntimeException( e );\n&gt;    }\n&gt;\n&gt; (Not sure this will cause the Heritrix log to capture the original \n&gt; message, but it might.)\n&gt;\n&gt; - Gordon @ IA\n&gt;\n&gt; nfoscarini wrote:\n&gt;   \n&gt;&gt; Hi,\n&gt;&gt;\n&gt;&gt; I would like to make a change request to some of the source code in\n&gt;&gt; Heritrix 2.0, but I&#39;m not sure how to do this. Do I open a Jira issue,\n&gt;&gt; or is there a way to submit code to CVS for the developers to review?\n&gt;&gt;\n&gt;&gt; Anyway, here is my change request.\n&gt;&gt;\n&gt;&gt; Description:\n&gt;&gt;\n&gt;&gt; Developers creating add-ons sometimes need to throw exceptions to\n&gt;&gt; report to Heritrix that a recoverable exception has happen. Heritrix\n&gt;&gt; then logs this error into the &quot;runtime-errors.log&quot; has an -5 code on\n&gt;&gt; the URI.\n&gt;&gt;\n&gt;&gt; I would like to change the description that is logged, because it\n&gt;&gt; contains the exception stack trace, but not the exception description.\n&gt;&gt;\n&gt;&gt; For example; If I catch an exception like &quot;null pointer&quot;, and can not\n&gt;&gt; handle the exception. I&#39;ll wrap the exception, and throw a\n&gt;&gt; RuntimeException. Like this.\n&gt;&gt;\n&gt;&gt; catch( NullPointerException e )\n&gt;&gt; {\n&gt;&gt; // do some stuff\n&gt;&gt; throw new RuntimeException( e.getLocalizedMessage() );\n&gt;&gt; }\n&gt;&gt;\n&gt;&gt; Afterwards, when reviewing the &quot;runtime-errors.log&quot; the entry would\n&gt;&gt; look something like this.\n&gt;&gt;\n&gt;&gt; 2008-02-28T18:46:08.473Z    -5      18428 http://www.abc.com/ - -\n&gt;&gt; text/html #002 20080228184607809+440\n&gt;&gt; sha1:3SLSHIHACO4E3RJCBEHHX5WDZJKCD6RS - err=java.lang.RuntimeException,3t\n&gt;&gt;  java.lang.RuntimeException\n&gt;&gt;   at\n&gt;&gt; centipede.writer.Scripts3DWriterProcessor.innerProcess(Scripts3DWriterProcessor.java:266)\n&gt;&gt;   at org.archive.crawler.framework.Processor.process(Processor.java:112)\n&gt;&gt;   at\n&gt;&gt; org.archive.crawler.framework.ToeThread.processCrawlUri(ToeThread.java:302)\n&gt;&gt;   at org.archive.crawler.framework.ToeThread.run(ToeThread.java:151)\n&gt;&gt;\n&gt;&gt; Change effects:\n&gt;&gt; org.archive.crawler.framework.recoverableProblem(Throwable e)\n&gt;&gt;\n&gt;&gt; My problem with this log entry is that it doesn&#39;t describe the cause\n&gt;&gt; of the exception. If your library doesn&#39;t contain debug information,\n&gt;&gt; then the stack trace won&#39;t provide where the problem happened.\n&gt;&gt;\n&gt;&gt; So I recommend using e.getLocalizedMessage() in the log file, along\n&gt;&gt; with the stack trace.\n&gt;&gt;\n&gt;&gt; Current source code:\n&gt;&gt;\n&gt;&gt;     private void recoverableProblem(Throwable e) {\n&gt;&gt;         Object previousStep = step;\n&gt;&gt;         setStep(STEP_HANDLING_RUNTIME_EXCEPTION);\n&gt;&gt;         e.printStackTrace(System.err);\n&gt;&gt;         currentCuri.setFetchStatus(S_RUNTIME_EXCEPTION);\n&gt;&gt;         // store exception temporarily for logging\n&gt;&gt;         currentCuri.getAnnotations().add(&quot;err=&quot;+e.getClass().getName());\n&gt;&gt;         currentCuri.getData().put(A_RUNTIME_EXCEPTION, e);\n&gt;&gt;         String message = &quot;Problem &quot; + e + \n&gt;&gt;                 &quot; occured when trying to process &#39;&quot;\n&gt;&gt;                 + currentCuri.toString()\n&gt;&gt;                 + &quot;&#39; at step &quot; + previousStep \n&gt;&gt;                 + &quot; in &quot; + currentProcessorName +&quot;&#92;n&quot;;\n&gt;&gt;         logger.log(Level.SEVERE, message.toString(), e);\n&gt;&gt;     }\n&gt;&gt;\n&gt;&gt; Desired change:\n&gt;&gt;\n&gt;&gt;     private void recoverableProblem(Throwable e) {\n&gt;&gt;         Object previousStep = step;\n&gt;&gt;         setStep(STEP_HANDLING_RUNTIME_EXCEPTION);\n&gt;&gt;         e.printStackTrace(System.err);\n&gt;&gt;         currentCuri.setFetchStatus(S_RUNTIME_EXCEPTION);\n&gt;&gt;         // store exception temporarily for logging\n&gt;&gt;         currentCuri.getAnnotations().add(&quot;err=&quot;+e.getClass().getName());\n&gt;&gt;         currentCuri.getData().put(A_RUNTIME_EXCEPTION, e);\n&gt;&gt;         String message = &quot;Problem &quot; + e.getLocalizedMessage() + \n&gt;&gt;                 &quot; occured when trying to process &#39;&quot;\n&gt;&gt;                 + currentCuri.toString()\n&gt;&gt;                 + &quot;&#39; at step &quot; + previousStep \n&gt;&gt;                 + &quot; in &quot; + currentProcessorName +&quot;&#92;n&quot;;\n&gt;&gt;         logger.log(Level.SEVERE, message.toString(), e);\n&gt;&gt;     }\n&gt;&gt;\n&gt;&gt;\n&gt;&gt;\n&gt;&gt;\n&gt;&gt;  \n&gt;&gt; Yahoo! Groups Links\n&gt;&gt;\n&gt;&gt;\n&gt;&gt;\n&gt;&gt;     \n&gt;\n&gt;\n&gt;  \n&gt; Yahoo! Groups Links\n&gt;\n&gt;\n&gt;\n&gt;   \n\n"}}