{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":343342970,"authorName":"Jean-NoÃ«l Rivasseau","from":"&quot;=?UTF-8?Q?Jean-No=C3=ABl_Rivasseau?=&quot; &lt;elvanor@...&gt;","replyTo":"LIST","senderId":"_fB0uujgVe0TpMvuyKAtiH9pS8bBPeH4F2c4pzfKEKxlcVRWo6xAouLUb90sqf1RdsQEEspDQyien7OrMB9nDsboaJnr-q17EDPlbvQgydkd-318TVH6KL-MnqUTDm6G_A","spamInfo":{"isSpam":false,"reason":"12"},"subject":"Exception when instantiating Processor (when launching crawl job with a custom processor)","postDate":"1210773793","msgId":5205,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGQ2MWM1NzMwMDgwNTE0MDcwM3A0OWUxYzFjZXAxMDIzNjAxZTdkYWFkOThlQG1haWwuZ21haWwuY29tPg=="},"prevInTopic":0,"nextInTopic":5208,"prevInTime":5204,"nextInTime":5206,"topicId":5205,"numMessagesInTopic":9,"msgSnippet":"Hello, I am very new to Heritrix and am using 2.0.0. When I launch a job I get the following exception: I noticed this happens whenever I have a constructor","rawEmail":"Return-Path: &lt;elvanor@...&gt;\r\nX-Sender: elvanor@...\r\nX-Apparently-To: archive-crawler@yahoogroups.com\r\nX-Received: (qmail 72939 invoked from network); 14 May 2008 14:03:20 -0000\r\nX-Received: from unknown (66.218.67.97)\n  by m52.grp.scd.yahoo.com with QMQP; 14 May 2008 14:03:20 -0000\r\nX-Received: from unknown (HELO yw-out-2324.google.com) (74.125.46.29)\n  by mta18.grp.scd.yahoo.com with SMTP; 14 May 2008 14:03:20 -0000\r\nX-Received: by yw-out-2324.google.com with SMTP id 2so1821433ywt.87\n        for &lt;archive-crawler@yahoogroups.com&gt;; Wed, 14 May 2008 07:03:19 -0700 (PDT)\r\nX-Received: by 10.150.228.2 with SMTP id a2mr962592ybh.245.1210773796381;\n        Wed, 14 May 2008 07:03:16 -0700 (PDT)\r\nX-Received: by 10.150.136.9 with HTTP; Wed, 14 May 2008 07:03:13 -0700 (PDT)\r\nMessage-ID: &lt;d61c57300805140703p49e1c1cep1023601e7daad98e@...&gt;\r\nDate: Wed, 14 May 2008 16:03:13 +0200\r\nTo: archive-crawler@yahoogroups.com\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\nContent-Disposition: inline\r\nX-Google-Sender-Auth: a0f8d931d5a7b179\r\nX-eGroups-Msg-Info: 1:12:0:0:0\r\nX-eGroups-From: &quot;=?UTF-8?Q?Jean-No=C3=ABl_Rivasseau?=&quot; &lt;jean-noel.rivasseau@...&gt;\r\nFrom: &quot;=?UTF-8?Q?Jean-No=C3=ABl_Rivasseau?=&quot; &lt;elvanor@...&gt;\r\nSubject: Exception when instantiating Processor (when launching crawl job with a custom processor)\r\nX-Yahoo-Group-Post: member; u=343342970\r\n\r\nHello, I am very new to Heritrix and am using 2.0.0. When I launch a\njob I get the following exception:\n\nI noticed this happens whenever I have a constructor defined in my\ncustom Processor class that extends org.archive.modules.Processor.\n\nThis happens even if the constructor code is totally empty. If I\nremove the constructor everything works. However having a constructor\nto perform initialization would be nice...\n\nAm I doing something wrong? Any help appreciated.\n\nThanks,\n\nJean-Noel\n\njavax.management.ReflectionException\n\nnull\n\njavax.management.ReflectionException\n\tat org.archive.settings.jmx.LoggingDynamicMBean.dealWithException(LoggingDynamicMBean.java:77)\n\tat org.archive.settings.jmx.LoggingDynamicMBean.invoke(LoggingDynamicMBean.java:160)\n\tat com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:836)\n\tat com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:761)\n\tat org.archive.openmbeans.annotations.BeanProxy.invoke(BeanProxy.java:87)\n\tat $Proxy9.launchJob(Unknown Source)\n\tat org.archive.crawler.webui.CrawlerArea.launch(CrawlerArea.java:155)\n\tat jsp.crawler_005farea.do_005flaunch_jsp._jspService(jsp.crawler_005farea.do_005flaunch_jsp:45)\n\tat org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:809)\n\tat org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:459)\n\tat org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1054)\n\tat org.archive.crawler.webui.AuthFilter.doFilter(AuthFilter.java:79)\n\tat org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1045)\n\tat org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:358)\n\tat org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:231)\n\tat org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:629)\n\tat org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:453)\n\tat org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)\n\tat org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:141)\n\tat org.mortbay.jetty.Server.handle(Server.java:303)\n\tat org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:452)\n\tat org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:721)\n\tat org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:509)\n\tat org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:209)\n\tat org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:349)\n\tat org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:217)\n\tat org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:475)\nCaused by: java.lang.IllegalStateException\n\t... 28 more\n\n"}}