{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":254719850,"authorName":"steve@archive.org","from":"&quot;steve@...&quot; &lt;steve@...&gt;","profile":"stearcorg","replyTo":"LIST","senderId":"pnBmEcDVwA5hmPiA4IyxmMEK0NSuZ0lf5GTU4jzKIZo58h6SIpkH4ruH15HbIrlxghP5MkAFVkJVk1_E_6eyGfeo8rFxdvaqKNp1qulR","spamInfo":{"isSpam":false,"reason":"3"},"subject":"Re: [archive-crawler] Unhandled exception while running Heritrix","postDate":"1274484125","msgId":6533,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PDRCRjcxNTlELjMwNjA2MDlAYXJjaGl2ZS5vcmc+","inReplyToHeader":"PGh0MDM5NSs0amptQGVHcm91cHMuY29tPg==","referencesHeader":"PGh0MDM5NSs0amptQGVHcm91cHMuY29tPg=="},"prevInTopic":6526,"nextInTopic":6538,"prevInTime":6532,"nextInTime":6534,"topicId":6526,"numMessagesInTopic":6,"msgSnippet":"hi Sriram, hard to say what might have gone wrong from the job log. please check the heritrix_out.log for any errors as well. what version of heritrix are you","rawEmail":"Return-Path: &lt;steve@...&gt;\r\nX-Sender: steve@...\r\nX-Apparently-To: archive-crawler@yahoogroups.com\r\nX-Received: (qmail 42610 invoked from network); 21 May 2010 23:22:37 -0000\r\nX-Received: from unknown (98.137.34.46)\n  by m14.grp.re1.yahoo.com with QMQP; 21 May 2010 23:22:37 -0000\r\nX-Received: from unknown (HELO mail.archive.org) (207.241.231.239)\n  by mta3.grp.sp2.yahoo.com with SMTP; 21 May 2010 23:22:37 -0000\r\nX-Received: from localhost (localhost [127.0.0.1])\n\tby mail.archive.org (Postfix) with ESMTP id 73CEA29D89\n\tfor &lt;archive-crawler@yahoogroups.com&gt;; Fri, 21 May 2010 16:22:06 -0700 (PDT)\r\nX-Received: from mail.archive.org ([127.0.0.1])\n\tby localhost (mail.archive.org [127.0.0.1]) (amavisd-new, port 10024)\n\twith LMTP id V2W-yrB7Obww for &lt;archive-crawler@yahoogroups.com&gt;;\n\tFri, 21 May 2010 16:22:06 -0700 (PDT)\r\nX-Received: from SiznaxMBP.local (router300.sf.archive.org [208.70.27.190])\n\tby mail.archive.org (Postfix) with ESMTPSA id 04A8029D7D\n\tfor &lt;archive-crawler@yahoogroups.com&gt;; Fri, 21 May 2010 16:22:06 -0700 (PDT)\r\nMessage-ID: &lt;4BF7159D.3060609@...&gt;\r\nDate: Fri, 21 May 2010 16:22:05 -0700\r\nUser-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.1.9) Gecko/20100317 Thunderbird/3.0.4\r\nMIME-Version: 1.0\r\nTo: archive-crawler@yahoogroups.com\r\nReferences: &lt;ht0395+4jjm@...&gt;\r\nIn-Reply-To: &lt;ht0395+4jjm@...&gt;\r\nContent-Type: text/plain; charset=ISO-8859-1; format=flowed\r\nContent-Transfer-Encoding: 7bit\r\nX-eGroups-Msg-Info: 2:3:4:0:0\r\nFrom: &quot;steve@...&quot; &lt;steve@...&gt;\r\nSubject: Re: [archive-crawler] Unhandled exception while running Heritrix\r\nX-Yahoo-Group-Post: member; u=254719850; y=34rCvVWns8WVSycRWEIxmcB8lsftup8XGRYfvgKA2ITI\r\nX-Yahoo-Profile: stearcorg\r\n\r\nhi Sriram,\n\nhard to say what might have gone wrong from the job log.\nplease check the heritrix_out.log for any errors as well.\nwhat version of heritrix are you running, on which platform?\nmaybe attach your order.xml file for us to look at too.\n\n/steve@...\n\n\n\nOn 5/19/10 12:16 AM, sriram_varahan1 wrote:\n&gt;\n&gt;\n&gt; Hello,\n&gt;\n&gt; I have been running Heritrix for some time and recently I got this\n&gt; strange exception while launching a job. The details from the job.log\n&gt; are as follows:\n&gt;\n&gt; 2010-05-18T15:43:47.929Z SEVERE Unhandled exception or error intercepted\n&gt; 2010-05-18T15:43:47.993Z INFO Job instance discarded\n&gt; 2010-05-18T15:43:48.364Z INFO Job instantiated\n&gt; 2010-05-18T15:43:48.452Z INFO Job launched\n&gt; 2010-05-18T15:43:48.576Z SEVERE RuntimeException:\n&gt; com.sleepycat.je.EnvironmentFailureException: (JE 4.0.71) Environment\n&gt; must be closed, caused by: com.sleepycat.je.EnvironmentFailureException:\n&gt; Environment invalid because of previous exception: (JE 4.0.71)\n&gt; /root/test_job/state com.sleepycat.je.log.ChecksumException: Read\n&gt; invalid log entry type: 99 LOG_CHECKSUM: Checksum invalid on read, log\n&gt; is likely invalid. Environment is invalid and must be closed.\n&gt; fetchTarget of 0x0/0x40904a parent IN=13 IN\n&gt; class=com.sleepycat.je.tree.BIN lastFullVersion=0x2/0xb1fb2\n&gt; parent.getDirty()=false state=0 (in thread &#39;test_job launchthread&#39;)\n&gt; 2010-05-18T15:43:50.051Z SEVERE Unhandled exception or error intercepted\n&gt;\n&gt; Can someone please shed some light on the error and what I would need to\n&gt; do to avoid this in the future.\n&gt;\n&gt; Thanks,\n&gt; Sriram.\n\n"}}