{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":137285340,"authorName":"Gordon Mohr","from":"Gordon Mohr &lt;gojomo@...&gt;","profile":"gojomo","replyTo":"LIST","senderId":"Kw3-rT87zEji4qrXRum26rozffH5Of7ZGilgwnKuzKniUII7UG7fvm9OUShHizcD6IGgHclfabQ8nuhHj2mTwNr_ButxzwM","spamInfo":{"isSpam":false,"reason":"0"},"subject":"Re: [archive-crawler] Re: Unhandled exception while running Heritrix","postDate":"1274911822","msgId":6546,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PDRCRkQ5QzRFLjEwNDA2MDBAYXJjaGl2ZS5vcmc+","inReplyToHeader":"PGh0aWMxays4YmNxQGVHcm91cHMuY29tPg==","referencesHeader":"PGh0aWMxays4YmNxQGVHcm91cHMuY29tPg=="},"prevInTopic":6541,"nextInTopic":6551,"prevInTime":6545,"nextInTime":6547,"topicId":6526,"numMessagesInTopic":6,"msgSnippet":"What Java VM? The initial error you reported is suggestive that there was some corruption in the BDB database files, which caused an earlier exception that","rawEmail":"Return-Path: &lt;gojomo@...&gt;\r\nX-Sender: gojomo@...\r\nX-Apparently-To: archive-crawler@yahoogroups.com\r\nX-Received: (qmail 77593 invoked from network); 26 May 2010 22:10:26 -0000\r\nX-Received: from unknown (66.196.94.106)\n  by m4.grp.sp2.yahoo.com with QMQP; 26 May 2010 22:10:26 -0000\r\nX-Received: from unknown (HELO relay03.pair.com) (209.68.5.17)\n  by mta2.grp.re1.yahoo.com with SMTP; 26 May 2010 22:10:26 -0000\r\nX-Received: (qmail 75470 invoked from network); 26 May 2010 22:10:22 -0000\r\nX-Received: from 208.70.27.190 (HELO silverbook.local) (208.70.27.190)\n  by relay03.pair.com with SMTP; 26 May 2010 22:10:22 -0000\r\nX-pair-Authenticated: 208.70.27.190\r\nMessage-ID: &lt;4BFD9C4E.1040600@...&gt;\r\nDate: Wed, 26 May 2010 15:10:22 -0700\r\nUser-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.1.9) Gecko/20100317 Thunderbird/3.0.4\r\nMIME-Version: 1.0\r\nTo: archive-crawler@yahoogroups.com\r\nCc: sriram_varahan1 &lt;sriram_varahan1@...&gt;\r\nReferences: &lt;htic1k+8bcq@...&gt;\r\nIn-Reply-To: &lt;htic1k+8bcq@...&gt;\r\nContent-Type: text/plain; charset=ISO-8859-1; format=flowed\r\nContent-Transfer-Encoding: 7bit\r\nFrom: Gordon Mohr &lt;gojomo@...&gt;\r\nSubject: Re: [archive-crawler] Re: Unhandled exception while running Heritrix\r\nX-Yahoo-Group-Post: member; u=137285340; y=KoOpoghr6s_GJPoUzk6bSSVvV5cdGv7JdodByMGlWxik\r\nX-Yahoo-Profile: gojomo\r\n\r\nWhat Java VM?\n\nThe initial error you reported is suggestive that there was some \ncorruption in the BDB database files, which caused an earlier exception \nthat fouled the environment. Then, a later operation got the error you \nexcerpted.\n\nSo, finding the first exception will give the best clue as to what went \nwrong -- but it could have been some random/arbitrary error like \nRAM/IO-bus/disk flakiness.\n\nYou can move jobs directories around, but shouldn&#39;t do so while Heritrix \nis running; it&#39;s generally not expecting the job directories and job \nfiles it&#39;s already discovered to be changed outside its own operations.\n\nThere&#39;s not yet any in-UI facility for completely deleting a job. The \nsafest approach at this time would be (1) quit the Heritrix JVM at a \nconvenient time; (2) delete the job(s) files/directories; (3) restart \nthe Heritrix JVM.\n\n- Gordon @ IA\n\nOn 5/25/10 10:36 PM, sriram_varahan1 wrote:\n&gt;\n&gt;\n&gt; Hi Steve,\n&gt;\n&gt; I am using Heritrix 3.1.1. I am running it under Linux.\n&gt;\n&gt; Maybe the way I am using it could cause an issue. I run a job and then\n&gt; delete the job from the directory and move it to another location. Then\n&gt; when I need to perform the job again I copy it back.\n&gt;\n&gt; Is this known to cause any issue?\n&gt;\n&gt; Is there a clean way of deleting a job in Heritrix 3?\n&gt;\n&gt; I am operating it using scripts and issuing commands through curl.\n&gt;\n&gt;\n&gt; Thanks,\n&gt; Sriram\n&gt;\n&gt;\n&gt; --- In archive-crawler@yahoogroups.com, &quot;steve@...&quot; &lt;steve@...&gt; wrote:\n&gt;  &gt;\n&gt;  &gt; hi Sriram,\n&gt;  &gt;\n&gt;  &gt; hard to say what might have gone wrong from the job log.\n&gt;  &gt; please check the heritrix_out.log for any errors as well.\n&gt;  &gt; what version of heritrix are you running, on which platform?\n&gt;  &gt; maybe attach your order.xml file for us to look at too.\n&gt;  &gt;\n&gt;  &gt; /steve@...\n&gt;  &gt;\n&gt;  &gt;\n&gt;  &gt;\n&gt;  &gt; On 5/19/10 12:16 AM, sriram_varahan1 wrote:\n&gt;  &gt; &gt;\n&gt;  &gt; &gt;\n&gt;  &gt; &gt; Hello,\n&gt;  &gt; &gt;\n&gt;  &gt; &gt; I have been running Heritrix for some time and recently I got this\n&gt;  &gt; &gt; strange exception while launching a job. The details from the job.log\n&gt;  &gt; &gt; are as follows:\n&gt;  &gt; &gt;\n&gt;  &gt; &gt; 2010-05-18T15:43:47.929Z SEVERE Unhandled exception or error\n&gt; intercepted\n&gt;  &gt; &gt; 2010-05-18T15:43:47.993Z INFO Job instance discarded\n&gt;  &gt; &gt; 2010-05-18T15:43:48.364Z INFO Job instantiated\n&gt;  &gt; &gt; 2010-05-18T15:43:48.452Z INFO Job launched\n&gt;  &gt; &gt; 2010-05-18T15:43:48.576Z SEVERE RuntimeException:\n&gt;  &gt; &gt; com.sleepycat.je.EnvironmentFailureException: (JE 4.0.71) Environment\n&gt;  &gt; &gt; must be closed, caused by:\n&gt; com.sleepycat.je.EnvironmentFailureException:\n&gt;  &gt; &gt; Environment invalid becau se of previous exception: (JE 4.0.71)\n&gt;  &gt; &gt; /root/test_job/state com.sleepycat.je.log.ChecksumException: Read\n&gt;  &gt; &gt; invalid log entry type: 99 LOG_CHECKSUM: Checksum invalid on read, log\n&gt;  &gt; &gt; is likely invalid. Environment is invalid and must be closed.\n&gt;  &gt; &gt; fetchTarget of 0x0/0x40904a parent IN=13 IN\n&gt;  &gt; &gt; class=com.sleepycat.je.tree.BIN lastFullVersion=0x2/0xb1fb2\n&gt;  &gt; &gt; parent.getDirty()=false state=0 (in thread &#39;test_job launchthread&#39;)\n&gt;  &gt; &gt; 2010-05-18T15:43:50.051Z SEVERE Unhandled exception or error\n&gt; intercepted\n&gt;  &gt; &gt;\n&gt;  &gt; &gt; Can someone please shed some light on the error and what I would\n&gt; need to\n&gt;  &gt; &gt; do to avoid this in the future.\n&gt;  &gt; &gt;\n&gt;  &gt; &gt; Thanks,\n&gt;  &gt; &gt; Sriram.\n&gt;  &gt;\n&gt;\n&gt;\n&gt; \n\n"}}