{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":500983475,"authorName":"David Pane","from":"David Pane &lt;dpane@...&gt;","profile":"david_pane1","replyTo":"LIST","senderId":"nVmYiNbgzGX3Krs2o8S_VEFuhTXmtzwlw08S-6rqfuVTG-lPPuD3g-tO-Gmg-TMCmfY6Dio4OtRyPIxLoSB8pyP9tWY","spamInfo":{"isSpam":false,"reason":"2"},"subject":"Re: cannot recover from checkpoint","postDate":"1327008265","msgId":7536,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PDRGMTg4QTA5LjUwMDAwMDVAY3MuY211LmVkdT4=","inReplyToHeader":"PDRGMTcxQ0UyLjIwOTAwMDZAY3MuY211LmVkdT4=","referencesHeader":"PDRGMTcxQ0UyLjIwOTAwMDZAY3MuY211LmVkdT4="},"prevInTopic":7532,"nextInTopic":7541,"prevInTime":7535,"nextInTime":7537,"topicId":7532,"numMessagesInTopic":6,"msgSnippet":"I was finally able to get instance #1 restarted. Although I did a number of things before successfully restoring I believe that the main source of the failure","rawEmail":"Return-Path: &lt;dpane@...&gt;\r\nX-Sender: dpane@...\r\nX-Apparently-To: archive-crawler@yahoogroups.com\r\nX-Received: (qmail 48676 invoked from network); 19 Jan 2012 21:24:30 -0000\r\nX-Received: from unknown (98.137.34.46)\n  by m3.grp.sp2.yahoo.com with QMQP; 19 Jan 2012 21:24:30 -0000\r\nX-Received: from unknown (HELO smtp.andrew.cmu.edu) (128.2.11.61)\n  by mta3.grp.sp2.yahoo.com with SMTP; 19 Jan 2012 21:24:29 -0000\r\nX-Received: from [128.2.209.200] (SAVOY.LTI.CS.CMU.EDU [128.2.209.200])\n\t(user=dpane mech=PLAIN (0 bits))\n\tby smtp.andrew.cmu.edu (8.14.4/8.14.4) with ESMTP id q0JLOOcK013198\n\t(version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-SHA bits=256 verify=NOT);\n\tThu, 19 Jan 2012 16:24:24 -0500\r\nMessage-ID: &lt;4F188A09.5000005@...&gt;\r\nDate: Thu, 19 Jan 2012 16:24:25 -0500\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:9.0) Gecko/20111222 Thunderbird/9.0.1\r\nMIME-Version: 1.0\r\nTo: archive-crawler@yahoogroups.com\r\nCc: Gordon Mohr &lt;gojomo@...&gt;, Noah Levitt &lt;nlevitt@...&gt;\r\nReferences: &lt;4F171CE2.2090006@...&gt;\r\nIn-Reply-To: &lt;4F171CE2.2090006@...&gt;\r\nContent-Type: text/plain; charset=ISO-8859-1; format=flowed\r\nContent-Transfer-Encoding: 7bit\r\nX-PMX-Version: 5.5.9.388399, Antispam-Engine: 2.7.2.376379, Antispam-Data: 2011.3.18.170322\r\nX-SMTP-Spam-Clean: 8% (\n KNOWN_FREEWEB_URI 0.05, BODY_SIZE_10000_PLUS 0, ECARD_KNOWN_DOMAINS 0, __BOUNCE_CHALLENGE_SUBJ 0, __BOUNCE_NDR_SUBJ_EXEMPT 0, __C230066_P5 0, __CP_URI_IN_BODY 0, __CT 0, __CTE 0, __CT_TEXT_PLAIN 0, __HAS_MSGID 0, __KNOWN_FREEWEB_URI4 0, __KNOWN_FREEWEB_URI7 0, __MIME_TEXT_ONLY 0, __MIME_VERSION 0, __MOZILLA_MSGID 0, __PHISH_PHRASE3 0, __SANE_MSGID 0, __TO_MALFORMED_2 0, __TO_NO_NAME 0, __URI_NO_MAILTO 0, __URI_NO_WWW 0, __USER_AGENT 0)\r\nX-SMTP-Spam-Score: 8%\r\nX-Scanned-By: MIMEDefang 2.60 on 128.2.11.61\r\nX-eGroups-Msg-Info: 2:2:2:0:2\r\nFrom: David Pane &lt;dpane@...&gt;\r\nSubject: Re: cannot recover from checkpoint\r\nX-Yahoo-Group-Post: member; u=500983475; y=XNctmiQKNBczMPswYICMYz69JYb17-GqFo7_C7AyiekWZZW1AGLGXg\r\nX-Yahoo-Profile: david_pane1\r\n\r\nI was finally able to get instance #1 restarted.\n\nAlthough I did a number of things before successfully restoring I \nbelieve that the main source of the failure was the duplicate key \n&quot;??text/javascript&quot; error&quot;.  It is unclear what caused this duplicate \nkey, but it appears that the following few checkpoints of the restarted \ninstance dose not have this duplicate entry anymore.\n\n\nTo ensure that I didn&#39;t corrupt the current state of the crawl state, I \ncopied the following to a new directory /basepath/2011-12-23/.\n\n&quot;action&quot; directory\n&quot;checkpoints&quot; directory\n&quot;crawler-beans.cxml&quot; file\n&quot;diversions&quot; directory\n&quot;blacklist-optout.surt&quot; file\n&quot;seeds.txt&quot; file\n\nI created a the directory &quot;state&quot; and copied the desired recovery \ncheckpoint directory from the original state directory into the newly \ncreate state directory.\n\nTo eliminate the java.lang.RuntimeException: org.json.JSONException: \nDuplicate key &quot;??text/javascript&quot; error, I removed the second entry of \nof each of these:\n&quot;??text/javascript&quot;:1,\n&quot;??text/javascript&quot;:74208,\n\nfrom the file  /path to jobs \ndirectory/2011-12-23/checkpoints/statisticsTracker\n\nFinally, I was having problems with a couple of files in the\n/path to jobs directory/2011-12-23/state/cp00001-201201xxxxxxxx directory.\n\nThe filenames look like this &quot;000eb572.jdb,9999781&quot; where I think the \n9999781 is suppose to represent the size of the file.\n\nWARNING thread-1ex6 org.archive.bdb.BdbModule.doRecover() \n000eb572.jdb,9999781 expected 9999781 actual 9999838\nWARNING thread-16 org.archive.bdb.BdbModule.doRecover() 000eb572.jdb \nexpected 9999781 actual 9999838\n\nAlthough these lines are not SEVER errors, I was wondering what would \ncause this?\n\n\nOn several unsuccessful attempts on recovering from this copied \ncheckpoint, I saw different files cause errors similar to this:\n\nSEVERE thread-12 org.archive.bdb.BdbModule.doRecover() unable to create \nrequired restore link /path to jobs directory/2011-12-23/state/000720e2.jdb\nSEVERE thread-16 org.archive.bdb.BdbModule.doRecover() unable to delete \nobstructing file /path to jobs directory/2011-12-23/state/0005915c.jdb\n\nIn order to eliminate these SEVERE errors, I deleted the individual \nfiles *.jdb in the state directory.  I also renamed the files in the \ncheckpoint directory to represent the correct size.  I modified the \nmanifest file in that directory to represent the newly named file.\n\nFailed attempts to restore from this checkpoint appeared to cause the \ncheckpoint files to change size and thus need to be renamed to avoid the \nwarning of expected vs actual size as explained above.\n\n\n--David\n\nOn 1/18/2012 2:26 PM, David Pane wrote:\n&gt; This morning I shut down all 5 instances. 4 recovered from the last\n&gt; checkpoint and are crawling. They are all running on less than\n&gt; configured threads due to the server errors I&#39;ve seen before.\n&gt;\n&gt; http://tech.groups.yahoo.com/group/archive-crawler/message/7493\n&gt;\n&gt; It is more severe than it was the last time.\n&gt;\n&gt; Instance #0 has 40 less - running with 1160.\n&gt; Instance #2 has 234 less - running with 234.\n&gt; Instance #3 has 111 less - running with 111.\n&gt; Instance #4 has 26 less - running with 26.\n&gt;\n&gt; -------------\n&gt; Instance #1:\n&gt; -------------\n&gt; When attempting to recover from &quot;any&quot; recent checkpoint, I get the\n&gt; following errors (see below) and the recover fails. Although this\n&gt; instance did not give me problems before, there were multiple SEVERE\n&gt; errors in the logs previous to me stopping the crawl. see attached file\n&gt; - I removed all INFO lines from the logs - sorry for the large\n&gt; attachment....\n&gt;\n&gt; I found that the mime-report has two entries for &quot;??text/javascript&quot;\n&gt;\n&gt;  &gt;&gt;&gt; grep javascript mimetype-report.txt.2012-01-17h19m05\n&gt; 726509 15900289997 application/x-javascript\n&gt; 277744 5991936365 application/javascript\n&gt; 127275 3432127316 text/javascript\n&gt; 561 146075 text/javascript+json\n&gt; 272 7486875 text/x-javascript\n&gt; 24 142128 javascript/text\n&gt; 15 155529 javascript\n&gt; 10 191371 ?text/javascript?\n&gt; 6 175283 javascript/x-javascript\n&gt; 4 80925 application/vnd.javascript\n&gt; 3 193869 type/javascript\n&gt; 1 74208 ??text/javascript\n&gt; 1 33306 txt/javascript\n&gt; 1 74208 ??text/javascript\n&gt;\n&gt; I am also ready to start a recover from the frontier.recover but I am\n&gt; hoping that there is a way around this problem.... any ideas?????\n&gt;\n&gt; --David\n&gt;\n&gt; Here is a sample of what is in the logs.\n&gt;\n&gt; Job.log:\n&gt;\n&gt; 2012-01-18T17:37:39.992Z SEVERE Failed to start bean\n&gt; &#39;statisticsTracker&#39;; nested exception is java.lang.RuntimeException:\n&gt; org.json.JSONException: Duplicate key &quot;??text/javascript&quot; (in thread\n&gt; &#39;2011-12-23 launchthread&#39;)\n&gt; 2012-01-18T17:37:39.992Z SEVERE Failed to start bean\n&gt; &#39;statisticsTracker&#39;; nested exception is java.lang.RuntimeException:\n&gt; org.json.JSONException: Duplicate key &quot;??text/javascript&quot;\n&gt; 2012-01-18T17:37:39.990Z INFO Job instance discarded\n&gt; 2012-01-18T17:04:00.791Z SEVERE unable to delete obstructing file\n&gt; /scratch/heritrix-3.1.1/jobs/2011-12-23/state/00088669.jdb (in thread\n&gt; &#39;2011-12-23 launchthread&#39;)\n&gt; 2012-01-18T17:03:55.033Z SEVERE unable to create required restore link\n&gt; /scratch/heritrix-3.1.1/jobs/2011-12-23/state/00081efd.jdb (in thread\n&gt; &#39;2011-12-23 launchthread&#39;)\n&gt; 2012-01-18T17:02:18.458Z INFO Job launched\n&gt; 2012-01-18T16:59:19.283Z INFO Job instantiated\n&gt;\n&gt;\n&gt;\n&gt; ---------------------------------------\n&gt; cat heritrix_out.log\n&gt;\n&gt; Wed Jan 18 11:59:05 EST 2012 Starting heritrix\n&gt; Linux compute-1-12.local 2.6.18-194.17.4.el5 #1 SMP Mon Oct 25 15:50:53\n&gt; EDT 2010 x86_64 GNU/Linux\n&gt; java version &quot;1.6.0_16&quot;\n&gt; Java(TM) SE Runtime Environment (build 1.6.0_16-b01)\n&gt; Java HotSpot(TM) 64-Bit Server VM (build 14.2-b01, mixed mode)\n&gt; JAVA_OPTS=-Xmx55000M\n&gt; core file size (blocks, -c) 0\n&gt; data seg size (kbytes, -d) unlimited\n&gt; scheduling priority (-e) 0\n&gt; file size (blocks, -f) unlimited\n&gt; pending signals (-i) 530432\n&gt; max locked memory (kbytes, -l) unlimited\n&gt; max memory size (kbytes, -m) unlimited\n&gt; open files (-n) 4096\n&gt; pipe size (512 bytes, -p) 8\n&gt; POSIX message queues (bytes, -q) 819200\n&gt; real-time priority (-r) 0\n&gt; stack size (kbytes, -s) unlimited\n&gt; cpu time (seconds, -t) unlimited\n&gt; max user processes (-u) 530432\n&gt; virtual memory (kbytes, -v) unlimited\n&gt; file locks (-x) unlimited\n&gt; Sun Microsystems Inc. Java(TM) SE Runtime Environment 1.6.0_16-b01\n&gt; Using ad-hoc HTTPS certificate with fingerprint...\n&gt; SHA1:7E:D5:A0:17:AD:CB:03:7D:4C:AD:FB:E7:04:41:AB:0B:1A:42:78:B3\n&gt; Verify in browser before accepting exception.\n&gt; 2012-01-18 16:59:05.737 WARNING thread-10\n&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt; directory: ./jobs/var where job expected from: ./jobs/var\n&gt; 2012-01-18 16:59:05.758 WARNING thread-10\n&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt; directory: ./jobs/heritrix_dir where job expected from: ./jobs/heritrix_dir\n&gt; 2012-01-18 16:59:05.892 INFO thread-10\n&gt; org.archive.crawler.framework.Engine.addJobDirectory() added crawl job:\n&gt; 2011-12-23\n&gt; 2012-01-18 16:59:05.893 WARNING thread-10\n&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt; directory: ./jobs/heritrix_out.logSAVE~ where job expected from:\n&gt; ./jobs/heritrix_out.logSAVE~\n&gt; 2012-01-18 16:59:05.893 WARNING thread-10\n&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt; directory: ./jobs/heritrix_out.logSAVE where job expected from:\n&gt; ./jobs/heritrix_out.logSAVE\n&gt; 2012-01-18 16:59:05.894 WARNING thread-10\n&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt; directory: ./jobs/heritrix_out.log20120118 where job expected from:\n&gt; ./jobs/heritrix_out.log20120118\n&gt; 2012-01-18 16:59:05.894 WARNING thread-10\n&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt; directory: ./jobs/heritrix_out.log20120118no-INFO where job expected\n&gt; from: ./jobs/heritrix_out.log20120118no-INFO\n&gt; 2012-01-18 16:59:06.04::INFO: Logging to STDERR via\n&gt; org.mortbay.log.StdErrLog\n&gt; 2012-01-18 16:59:06.05::INFO: jetty-6.1.14\n&gt; 2012-01-18 16:59:06.369::INFO: Started SslSocketConnector@10.1.1.249:8443\n&gt; engine listening at port 8443\n&gt; operator login set per file @...\n&gt; Heritrix version: 3.1.1-SNAPSHOT-20111222.225453\n&gt; 2012-01-18 16:59:17.201 INFO thread-11\n&gt; org.springframework.context.support.AbstractApplicationContext.prepareRefresh()\n&gt; Refreshing org.archive.spring.PathSharingContext@44ed904: startup date\n&gt; [Wed Jan 18 16:59:17 GMT 2012]; root of context hierarchy\n&gt; 2012-01-18 16:59:19.283 INFO thread-11\n&gt; org.archive.crawler.framework.CrawlJob.instantiateContainer() Job\n&gt; instantiated\n&gt; 2012-01-18 17:02:18.458 INFO thread-12\n&gt; org.archive.crawler.framework.CrawlJob.launch() Job launched\n&gt; 2012-01-18 17:02:19.997 INFO thread-13\n&gt; org.archive.spring.PathSharingContext.initLaunchId() launch id\n&gt; 20120118170219\n&gt; 2012-01-18 17:02:20.047 INFO thread-13\n&gt; org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start()\n&gt; Starting beans in phase 0\n&gt; 2012-01-18 17:03:55.033 SEVERE thread-13\n&gt; org.archive.bdb.BdbModule.doRecover() unable to create required restore\n&gt; link /scratch/heritrix-3.1.1/jobs/2011-12-23/state/00081efd.jdb\n&gt; 2012-01-18 17:04:00.791 SEVERE thread-13\n&gt; org.archive.bdb.BdbModule.doRecover() unable to delete obstructing file\n&gt; /scratch/heritrix-3.1.1/jobs/2011-12-23/state/00088669.jdb\n&gt; 2012-01-18 17:34:12.297 INFO thread-13\n&gt; org.springframework.context.support.AbstractApplicationContext.doClose()\n&gt; Closing org.archive.spring.PathSharingContext@44ed904: startup date [Wed\n&gt; Jan 18 16:59:17 GMT 2012]; root of context hierarchy\n&gt; 2012-01-18 17:34:12.298 INFO thread-13\n&gt; org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop()\n&gt; Stopping beans in phase 0\n&gt; 2012-01-18 17:37:39.990 INFO thread-13\n&gt; org.archive.crawler.framework.CrawlJob.doTeardown() Job instance discarded\n&gt; 2012-01-18 17:37:39.992 SEVERE thread-13\n&gt; org.archive.crawler.framework.CrawlJob.beansException() Failed to start\n&gt; bean &#39;statisticsTracker&#39;; nested exception is\n&gt; java.lang.RuntimeException: org.json.JSONException: Duplicate key\n&gt; &quot;??text/javascript&quot;\n&gt; org.springframework.context.ApplicationContextException: Failed to start\n&gt; bean &#39;statisticsTracker&#39;; nested exception is\n&gt; java.lang.RuntimeException: org.json.JSONException: Duplicate key\n&gt; &quot;??text/javascript&quot;\n&gt; at\n&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:169)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:159)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:159)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:159)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.DefaultLifecycleProcessor.access$1(DefaultLifecycleProcessor.java:154)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:335)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:143)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:89)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1236)\n&gt;\n&gt; at org.archive.spring.PathSharingContext.start(PathSharingContext.java:112)\n&gt; at org.archive.crawler.framework.CrawlJob.startContext(CrawlJob.java:458)\n&gt; at org.archive.crawler.framework.CrawlJob$1.run(CrawlJob.java:432)\n&gt; Caused by: java.lang.RuntimeException: org.json.JSONException: Duplicate\n&gt; key &quot;??text/javascript&quot;\n&gt; at org.archive.checkpointing.Checkpoint.loadJson(Checkpoint.java:142)\n&gt; at\n&gt; org.archive.crawler.reporting.StatisticsTracker.start(StatisticsTracker.java:355)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:166)\n&gt;\n&gt; ... 11 more\n&gt; Caused by: org.json.JSONException: Duplicate key &quot;??text/javascript&quot;\n&gt; at org.json.JSONObject.putOnce(JSONObject.java:1076)\n&gt; at org.json.JSONObject.&lt;init&gt;(JSONObject.java:205)\n&gt; at org.json.JSONTokener.nextValue(JSONTokener.java:344)\n&gt; at org.json.JSONObject.&lt;init&gt;(JSONObject.java:205)\n&gt; at org.json.JSONObject.&lt;init&gt;(JSONObject.java:402)\n&gt; at org.archive.checkpointing.Checkpoint.loadJson(Checkpoint.java:140)\n&gt; ... 13 more\n&gt; Exception in thread &quot;2011-12-23 launchthread&quot;\n&gt; org.springframework.beans.factory.BeanCreationException: Error creating\n&gt; bean with name &#39;configPathConfigurer&#39; defined in URL\n&gt; [file:/scratch/heritrix-3.1.1/jobs/2011-12-23/crawler-beans.cxml]:\n&gt; Initialization of bean failed; nested exception is\n&gt; java.lang.IllegalStateException: BeanFactory not initialized or already\n&gt; closed - call &#39;refresh&#39; before accessing beans via the ApplicationContext\n&gt; at\n&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:527)\n&gt;\n&gt; at\n&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)\n&gt;\n&gt; at\n&gt; org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)\n&gt;\n&gt; at\n&gt; org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n&gt;\n&gt; at\n&gt; org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)\n&gt;\n&gt; at\n&gt; org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)\n&gt;\n&gt; at\n&gt; org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:148)\n&gt;\n&gt; at\n&gt; org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:86)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:303)\n&gt;\n&gt; at\n&gt; org.archive.crawler.framework.CrawlController.sendCrawlStateChangeEvent(CrawlController.java:326)\n&gt;\n&gt; at\n&gt; org.archive.crawler.framework.CrawlController.requestCrawlStart(CrawlController.java:347)\n&gt;\n&gt; at org.archive.crawler.framework.CrawlJob$1.run(CrawlJob.java:434)\n&gt; Caused by: java.lang.IllegalStateException: BeanFactory not initialized\n&gt; or already closed - call &#39;refresh&#39; before accessing beans via the\n&gt; ApplicationContext\n&gt; at\n&gt; org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:171)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.AbstractApplicationContext.containsBean(AbstractApplicationContext.java:1091)\n&gt;\n&gt; at\n&gt; org.springframework.context.support.AbstractApplicationContext$ApplicationListenerDetector.postProcessAfterInitialization(AbstractApplicationContext.java:1369)\n&gt;\n&gt; at\n&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:407)\n&gt;\n&gt; at\n&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1426)\n&gt;\n&gt; at\n&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)\n&gt;\n&gt; ... 11 more\n\n"}}